### ISSUE TITLE
can we have Asia Pacific (Mumbai)  ap-south-1 support as well?

### ISSUE THREAD

**Issue by MrSpark2591** [meteor/galaxy-roadmap#1]
We have been using galaxy from the past two years now. Right now we have to deploy our app in other nearest regions to host it on the galaxy. So is it possible to have this time zone support as well?

**Comment by filipenevola** [comment]
Hi @MrSpark2591 please submit your request here https://galaxy-guide.meteor.com/deploy-region.html#new_regions

Thanks.
